/*
 * test_ui.c — unit tests for the header's corner button and the Back-key
 * mapping. Links the real ui.c against a stub inkview.h generated by
 * run_host_tests.sh (with the device's real IV_KEY_* codes) and stub drawing
 * functions that just record the strings painted.
 *
 * The corner button is how InkStation is left by touch: Back on non-root
 * screens, Exit on the root (search) screen. Before it existed the app could
 * only be closed from the firmware task manager.
 */
#include <stdio.h>
#include <string.h>

#include "ui.h"

static int g_fail;

#define CHECK(cond, msg) do {                                  \
    if (cond) { printf("  ok   %s\n", msg); }                  \
    else      { printf("  FAIL %s\n", msg); g_fail++; }        \
} while (0)

/* ---- stubs ---------------------------------------------------------- */
static char g_drawn[4096];      /* every string DrawTextRect was asked to paint */

int  ScreenWidth(void)  { return 758; }
int  ScreenHeight(void) { return 1024; }
ifont *OpenFont(const char *n, int s, int a) { (void)n; (void)s; (void)a; return (ifont *)1; }
void CloseFont(ifont *f) { (void)f; }
void SetFont(ifont *f, int c) { (void)f; (void)c; }
void DrawTextRect(int x, int y, int w, int h, const char *s, int f)
{
    (void)x; (void)y; (void)w; (void)h; (void)f;
    if (s && strlen(g_drawn) + strlen(s) + 2 < sizeof g_drawn) {
        strcat(g_drawn, s);
        strcat(g_drawn, "\n");
    }
}
void DrawLine(int a, int b, int c, int d, int e) { (void)a; (void)b; (void)c; (void)d; (void)e; }
void DrawRect(int a, int b, int c, int d, int e) { (void)a; (void)b; (void)c; (void)d; (void)e; }
void FillArea(int a, int b, int c, int d, int e) { (void)a; (void)b; (void)c; (void)d; (void)e; }
void FullUpdate(void) {}

static int g_depth = 1;
int nav_depth(void) { return g_depth; }

/* On the 758 px stub screen the corner button spans x 606..734, y 12..60
 * (PAD_X 24, 128x48, centred in the 72 px header). */
enum { BTN_X = 670, BTN_Y = 36 };

int main(void)
{
    printf("root screen (search):\n");
    g_depth = 1;
    g_drawn[0] = '\0';
    ui_draw_header("InkStation");
    CHECK(strstr(g_drawn, "Exit\n") != NULL,          "header draws Exit");
    CHECK(strstr(g_drawn, "Back") == NULL,            "header draws no Back");
    CHECK(ui_exit_button_hit(BTN_X, BTN_Y),           "tap on Exit hits");
    CHECK(ui_exit_button_hit(600, 70),                "near-miss inside the margin still hits");
    CHECK(!ui_exit_button_hit(100, BTN_Y),            "tap left of the button is not Exit");
    CHECK(!ui_exit_button_hit(BTN_X, 300),            "tap below the header is not Exit");
    CHECK(!ui_back_button_hit(BTN_X, BTN_Y),          "no Back target on the root screen");

    printf("board screen (not root):\n");
    g_depth = 2;
    g_drawn[0] = '\0';
    ui_draw_header("Guildford");
    CHECK(strstr(g_drawn, "Back\n") != NULL,          "header draws Back");
    CHECK(strstr(g_drawn, "Exit") == NULL,            "header draws no Exit");
    CHECK(ui_back_button_hit(BTN_X, BTN_Y),           "tap on Back hits");
    CHECK(!ui_exit_button_hit(BTN_X, BTN_Y),          "no Exit target off the root screen");

    printf("hardware keys that leave a screen:\n");
    CHECK(ui_nav_classify(IV_KEY_BACK) == UI_NAV_BACK, "IV_KEY_BACK -> BACK");
    CHECK(ui_nav_classify(IV_KEY_HOME) == UI_NAV_BACK, "IV_KEY_HOME -> BACK");
    CHECK(ui_nav_classify(IV_KEY_OK)   != UI_NAV_BACK, "IV_KEY_OK is not BACK");

    if (g_fail) { printf("ui: FAILED (%d)\n", g_fail); return 1; }
    printf("ui: all passed\n");
    return 0;
}
